chat_config:
  backend: test
  test_config:
    predict_delay: 1
  openai_config:
    model: gpt-3.5-turbo-0125
    api_key: ""
    base_url: https://api.openai.com/v1
    proxy: ""
embed_config:
  backend: test
  openai_config:
    model: text-embedding-3-small
    api_key: ""
    base_url: https://api.openai.com/v1
    proxy: ""
